# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c16364ea8b83ba4cf2a2605f0cb8b81ef6c74ce1f841995dae6a7171fc948ccac93e760339b462f3d24e28957106006a338ef3566043f6255c317f48fd65fb5c

test:
  secret_key_base: 9c957fd9d2a055b54eb4318d1e9461bd8e3953c9a1ea16e9106d13087f1318e9ba270e3dd4a1d25de029e9834ae6ef2ccb6119722ee25934358740c0200621fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
